[project]
org-name = "ballerina"
version = "@toml.version@"

[dependencies]
"ballerina/http" = "@stdlib.http.version@"
"ballerina/mime" = "@stdlib.mime.version@"
"ballerina/auth" = "@stdlib.auth.version@"
"ballerina/file" = "@stdlib.file.version@"
"ballerina/cache" = "@stdlib.cache.version@"
"ballerina/crypto" = "@stdlib.crypto.version@"
"ballerina/encoding" = "@stdlib.encoding.version@"
"ballerina/task" = "@stdlib.task.version@"
"ballerina/log" = "@stdlib.log.version@"
"ballerina/time" = "@stdlib.time.version@"
"ballerina/reflect" = "@stdlib.reflect.version@"
"ballerina/runtime" = "@stdlib.runtime.version@"
"ballerina/system" = "@stdlib.system.version@"
"ballerina/config" = "@stdlib.configapi.version@"
"ballerina/io" = "@stdlib.io.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "web-sub"
    version = "@project.version@"
    path = "../websub-native/build/libs/websub-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "netty-common"
    version = "@netty.version@"
    path = "./lib/netty-common-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "netty-buffer"
    version = "@netty.version@"
    path = "./lib/netty-buffer-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "netty-transport"
    version = "@netty.version@"
    path = "./lib/netty-transport-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "netty-resolver"
    version = "@netty.version@"
    path = "./lib/netty-resolver-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "netty-handler"
    version = "@netty.version@"
    path = "./lib/netty-handler-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "netty-codec-http"
    version = "@netty.version@"
    path = "./lib/netty-codec-http-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "netty-codec"
    version = "@netty.version@"
    path = "./lib/netty-codec-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "netty-handler-proxy"
    version = "@netty.version@"
    path = "./lib/netty-handler-proxy-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "netty-codec-http2"
    version = "@netty.version@"
    path = "./lib/netty-codec-http2-@netty.version@.jar"
    groupId = "io.netty"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "commons-pool"
    version = "@wso2commonspool.version@"
    path = "./lib/commons-pool-@wso2commonspool.version@.jar"
    groupId = "commons-pool.wso2"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "snakeyaml"
    version = "@wso2snakeyaml.version@"
    path = "./lib/snakeyaml-@wso2snakeyaml.version@.jar"
    groupId = "org.wso2.orbit.org.yaml"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "bcprov-jdk15on"
    version = "@bouncycastle.version@"
    path = "./lib/bcprov-jdk15on-@bouncycastle.version@.jar"
    groupId = "org.bouncycastle"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "bcpkix-jdk15on"
    version = "@bouncycastle.version@"
    path = "./lib/bcpkix-jdk15on-@bouncycastle.version@.jar"
    groupId = "org.bouncycastle"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "netty-tcnative-boringssl-static"
    version = "@nettytcnative.version@"
    path = "./lib/netty-tcnative-boringssl-static-@nettytcnative.version@.jar"
    groupId = "io.netty"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "broker-core"
    version = "@ballerinambcore.version@"
    path = "./lib/broker-core-@ballerinambcore.version@.jar"
    groupId = "io.ballerina.messaging"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "broker-common"
    version = "@ballerinamb.version@"
    path = "./lib/broker-common-@ballerinamb.version@.jar"
    groupId = "io.ballerina.messaging"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "broker-auth"
    version = "@ballerinamb.version@"
    path = "./lib/broker-auth-@ballerinamb.version@.jar"
    groupId = "io.ballerina.messaging"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "broker-rest-runner"
    version = "@ballerinamb.version@"
    path = "./lib/broker-rest-runner-@ballerinamb.version@.jar"
    groupId = "io.ballerina.messaging"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "broker-coordination"
    version = "@ballerinamb.version@"
    path = "./lib/broker-coordination-@ballerinamb.version@.jar"
    groupId = "io.ballerina.messaging"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "org.wso2.carbon.metrics.core"
    version = "@wso2carbonmetrics.version@"
    path = "./lib/org.wso2.carbon.metrics.core-@wso2carbonmetrics.version@.jar"
    groupId = "org.wso2.carbon.metrics"
    modules = ["websub"]

    [[platform.libraries]]
    artifactId = "guava"
    version = "@guava.version@"
    path = "./lib/guava-@guava.version@.jar"
    groupId = "com.google.guava"
    modules = ["websub"]

